REM   Script: class 1
REM   rafsan vai er class

CREATE TABLE CUSTOMER( 
CUSTOMER_ID NUMBER(6) PRIMARY KEY, 
CUSTOMER_NAME VARCHAR2(30), 
CITY VARCHAR2(15) 
);

SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (1,'JAKE','JORPUKUR');

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (2,'JAKE','JORPUKUR');

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (3,'JAKY','JORPUKUR');

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (4,'JAKEKY','JORPUKUR');

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (5,'JAKNN','JORPUKUR');

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (6,'JAME','JORPUKUR');

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (7,'JAMY','JORPUKUR');

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (8,'JANE','JORPUKUR');

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (9,'JAME','HARINAL');

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (10,'JAMY','RAJBARI');

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (11,'JANE','BARISAL');

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (12,'JAME','CUMILLA');

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (13,'JAMY','NOAAKHALI');

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (14,'JANE','DHAKA');

SELECT CUSTOMER_ID,CITY FROM CUSTOMER;

SELECT * 
FROM CUSTOMER 
WHERE CUSTOMER_ID>=9 AND CUSTOMER_ID<=13;

UPDATE CUSTOMER 
SET CUSTOMER_NAME='JAKY CHANG' 
WHERE CUSTOMER_ID=3;

DELETE  
FROM CUSTOMER 
WHERE CUSTOMER_NAME='JAKY CHANG';

INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES (3,'KARIM RAKIB','JORPUKUR');

SELECT * FROM CUSTOMER  
ORDER BY CUSTOMER_ID ASC;

SELECT * FROM CUSTOMER  
ORDER BY CUSTOMER_ID DESC;

