REM   Script: Class 2
REM   2nd class

CREATE TABLE SUPPLIER ( 
SUP_ID NUMBER(10) PRIMARY KEY, 
SUP_NAME VARCHAR(20), 
SUP_CONTACT NUMBER(11) 
 
);

CREATE TABLE PRODUCT( 
 
P_ID NUMBER(10) PRIMARY KEY, 
P_NAME VARCHAR(20), 
P_PRICE NUMBER(6), 
SUP_ID NUMBER(10), 
 
CONSTRAINT FK_SUPPLIER 
FOREIGN KEY (SUP_ID) 
REFERENCE SUPPLIER(SUP_ID) 
 
);

CREATE TABLE SUPPLIER ( 
SUP_ID NUMBER(10) PRIMARY KEY, 
SUP_NAME VARCHAR(20), 
SUP_CONTACT NUMBER(11) 
 
);

CREATE TABLE PRODUCT( 
 
P_ID NUMBER(10) PRIMARY KEY, 
P_NAME VARCHAR(20), 
P_PRICE NUMBER(6), 
SUP_ID NUMBER(10) 
 
CONSTRAINT FK_SUPPLIER 
FOREIGN KEY (SUP_ID) 
REFERENCE SUPPLIER(SUP_ID) 
 
);

