CREATE TABLE DATABASE( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
LOCATION VARCHAR2(20, 
PHONE_NUMBER NUMBER 
);

CREATE TABLE STUDENT ( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3), 
);

INSERT INTO DATABASE(NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1 ,'CHAYABITHI',019);

CREATE TABLE DATABASE( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
LOCATION VARCHAR2(20), 
PHONE_NUMBER NUMBER 
);

CREATE TABLE STUDENT ( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3), 
);

INSERT INTO DATABASE(NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1 ,'CHAYABITHI',019);

CREATE TABLE DATABASE( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
LOCATION VARCHAR2(20), 
PHONE_NUMBER NUMBER 
);

CREATE TABLE STUDENT ( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3), 
);

INSERT INTO DATABASE(NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1 ,'CHAYABITHI',019);

CREATE TABLE STUDENT ( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3), 
);

CREATE TABLE STUDENT( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3), 
);

CREATE TABLE DATABASE( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
LOCATION VARCHAR2(20), 
PHONE_NUMBER NUMBER 
);

CREATE TABLE STUDENT( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3), 
);

CREATE TABLE STUDENT( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3) 
);

INSERT INTO DATABASE(NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1 ,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1 ,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('TUMI',10,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('HE',9,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('SHE',5,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('US',7,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('WE',4,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('THEY',6,'CHAYABITHI',019);

SELECT * FROM DATABASE;

DROP TABLE DATABASE


CREATE TABLE DATABASE( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
LOCATION VARCHAR2(20), 
PHONE_NUMBER NUMBER 
);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('TUMI',10,'CHAYABITHI',017);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('HE',9,'CHAYABITHI',016);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('SHE',5,'CHAYABITHI',014);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('US',7,'CHAYABITHI',013);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('WE',4,'CHAYABITHI',018);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('THEY',6,'CHAYABITHI',015);

SELECT * FROM DATABASE;

INSERT INTO STUDENT (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1,'CHAYABITHI',019);

INSERT INTO STUDENT (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('TUMI',10,'CHAYABITHI',017);

INSERT INTO STUDENT (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('HE',9,'CHAYABITHI',016);

INSERT INTO STUDENT (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('SHE',5,'CHAYABITHI',014);

INSERT INTO STUDENT (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('US',7,'CHAYABITHI',013);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('WE',4,'CHAYABITHI',018);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('THEY',6,'CHAYABITHI',015);

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'CHAYABITHI',019);

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'CHAYABITHI',017);

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'CHAYABITHI',016);

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'CHAYABITHI',014);

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'CHAYABITHI',013);

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('WE',4,'CHAYABITHI',018);

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('THEY',6,'CHAYABITHI',015);

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'CHAYABITHI',019);

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'CHA');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'CHAY');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'CH');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'CHAYA');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('WE',4,'CHI');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('THEY',6,'CHAI');

CREATE TABLE DATABASE( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
LOCATION VARCHAR2(20), 
PHONE_NUMBER NUMBER 
);

CREATE TABLE STUDENT( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3) 
);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('TUMI',10,'CHAYABITHI',017);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('HE',9,'CHAYABITHI',016);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('SHE',5,'CHAYABITHI',014);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('US',7,'CHAYABITHI',013);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('WE',4,'CHAYABITHI',018);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('THEY',6,'CHAYABITHI',015);

SELECT * FROM DATABASE;

SELECT * FROM DATABASE;

SELECT * FROM DATABASE;

DROP TABLE DATABASE 
 
INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'CHA')


DROP TABLE DATABASE 
 
INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'CHA')


DROP TABLE DATABASE 
 
INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'CHA')


INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'CHAY');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'CHAY');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'CHAY');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'CH');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'CH');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'CH');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'CHAYA');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'CHAYA');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'CHAYA');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('WE',4,'CHI');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('WE',4,'CHI');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('WE',4,'CHI');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('THEY',6,'CHAI');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('THEY',6,'CHAI');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('THEY',6,'CHAI');

CREATE TABLE DATABASE( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
LOCATION VARCHAR2(20), 
PHONE_NUMBER NUMBER 
);

CREATE TABLE DATABASE( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
LOCATION VARCHAR2(20), 
PHONE_NUMBER NUMBER 
);

CREATE TABLE STUDENT( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3) 
);

CREATE TABLE STUDENT( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3) 
);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('TUMI',10,'CHAYABITHI',017);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('TUMI',10,'CHAYABITHI',017);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('HE',9,'CHAYABITHI',016);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('HE',9,'CHAYABITHI',016);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('SHE',5,'CHAYABITHI',014);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('SHE',5,'CHAYABITHI',014);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('US',7,'CHAYABITHI',013);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('US',7,'CHAYABITHI',013);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('WE',4,'CHAYABITHI',018);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('WE',4,'CHAYABITHI',018);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('THEY',6,'CHAYABITHI',015);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('THEY',6,'CHAYABITHI',015);

SELECT * FROM DATABASE;

SELECT * FROM DATABASE;

DROP TABLE DATABASE 
 
INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'CHA')


DROP TABLE DATABASE 
 
INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'CHA')


INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'CHAY');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'CHAY');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'CH');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'CH');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'CHAYA');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'CHAYA');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('WE',4,'CHI');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('WE',4,'CHI');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('THEY',6,'CHAI');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('THEY',6,'CHAI');

CREATE TABLE DATABASE( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
LOCATION VARCHAR2(20), 
PHONE_NUMBER NUMBER 
);

CREATE TABLE STUDENT( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3) 
);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('TUMI',10,'CHAYABITHI',017);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('HE',9,'CHAYABITHI',016);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('SHE',5,'CHAYABITHI',014);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('US',7,'CHAYABITHI',013);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('WE',4,'CHAYABITHI',018);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('THEY',6,'CHAYABITHI',015);

SELECT * FROM DATABASE;

DROP TABLE DATABASE 
 
INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'CHA')


INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'CHAY');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'CH');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'CHAYA');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('WE',4,'CHI');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('THEY',6,'CHAI');

SELECT * FROM DATABASE 
WHERE ROLL>=15 AND ROLL <=18;

SELECT * FROM DATABASE 
WHERE ROLL>=15 AND ROLL <=18;

SELECT * FROM DATABASE 
WHERE ROLL>=15 AND ROLL <=18;

SELECT * FROM DATABASE 
WHERE ROLL>=15 AND ROLL <=18;

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'A');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'A');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'C');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('WE',4,'C');

INSERT INTO DATABASE (NAME,ROLL,SECTION) VALUES ('THEY',6,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'A');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'A');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('WE',4,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('THEY',6,'C');

SELECT * FROM STUDENT;

DROP TABLE STUDENT


CREATE TABLE STUDENT( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3) 
);

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'A');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'A');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('WE',4,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('THEY',6,'C');

SELECT * FROM STUDENT;

SELECT * FROM DATABASE 
WHERE ROLL>=15 AND ROLL <=18;

SELECT * FROM STUDENT 
WHERE SECTION='B';

SELECT * FROM DATABASE 
WHERE ROLL>=5 AND ROLL <=10;

SELECT LOCATION,NAME,PHONE_NUMBER FROM DATABASE 
WHERE SECTION='B;

SELECT LOCATION,NAME,PHONE_NUMBER FROM STUDENT 
WHERE SECTION='B;

SELECT LOCATION,NAME,PHONE_NUMBER FROM STUDENT 
WHERE SECTION='B';

SELECT NAME,LOCATION,PHONE_NUMBER FROM STUDENT AND DATABASE 
WHERE SECTION='B';

SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE SECTION='B';

SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (5,7);

SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (7,5);

SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (7,5);

SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (9,5);

SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (1,5);

SELECT SECTION FROM STUDENT 
WHERE ROLL IN (SELECT ROLL FROM DATABASE WHERE LOCATION='CHAYABITHI');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('THEY',8,'B');

UPDATE DATABSE  
SET LOCATION ='DHAKA' 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

UPDATE DATABSE  
SET LOCATION ='DHAKA' 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

SELECT * FROM DATABASE;

UPDATE DATABSE  
SET LOCATION ='DHAKA' 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

UPDATE DATABASE 
SET LOCATION ='DHAKA' 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

SELECT * FROM DATABASE;

UPDATE DATABASE 
SET PHONE_NUMBER =000 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='C');

SELECT * FROM DATABASE;

UPDATE DATABASE 
SET PHONE_NUMBER ='000' 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='C');

SELECT * FROM DATABASE;

UPDATE DATABASE 
SET PHONE_NUMBER ='AA' 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='C');

UPDATE DATABASE 
SET PHONE_NUMBER ='22' 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='C');

UPDATE DATABASE 
SET PHONE_NUMBER ='0D' 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='C');

UPDATE DATABASE 
SET PHONE_NUMBER =000 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='C');

DELETE FROM DATABASE 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='A');

CREATE TABLE DATABASE( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
LOCATION VARCHAR2(20), 
PHONE_NUMBER NUMBER 
);

CREATE TABLE STUDENT( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3) 
);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('TUMI',10,'CHAYABITHI',017);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('HE',9,'CHAYABITHI',016);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('SHE',5,'CHAYABITHI',014);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('US',7,'CHAYABITHI',013);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('WE',4,'CHAYABITHI',018);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('THEY',6,'CHAYABITHI',015);

SELECT * FROM DATABASE;

SELECT * FROM DATABASE;

DROP TABLE DATABASE 
DROP TABLE STUDENT 
 
INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'A')


DROP TABLE DATABASE 
DROP TABLE STUDENT 
 
INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'A')


INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'A');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'A');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('WE',4,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('WE',4,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('THEY',6,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('THEY',6,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('THEY',8,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('THEY',8,'B');

SELECT * FROM STUDENT;

SELECT * FROM STUDENT;

SELECT * FROM DATABASE 
WHERE ROLL>=5 AND ROLL <=10;

SELECT * FROM DATABASE 
WHERE ROLL>=5 AND ROLL <=10;

SELECT * FROM STUDENT 
WHERE SECTION='B' 
 
--- FIND OUT THE LOCATION , NAME AND PHONE NUMBER OF THE SECTION B STUDENT  
 
 
 
SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

SELECT * FROM STUDENT 
WHERE SECTION='B' 
 
--- FIND OUT THE LOCATION , NAME AND PHONE NUMBER OF THE SECTION B STUDENT  
 
 
 
SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (1,5) 
 
--- FIND OUT THE SECTION OF LOCATION CHAYABITHI 
 
SELECT SECTION FROM STUDENT 
WHERE ROLL IN (SELECT ROLL FROM DATABASE WHERE LOCATION='CHAYABITHI') 
 
--UPDATE THE LOCATION = DHAKA OF SECTION B 
 
UPDATE DATABASE 
SET LOCATION ='DHAKA' 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (1,5) 
 
--- FIND OUT THE SECTION OF LOCATION CHAYABITHI 
 
SELECT SECTION FROM STUDENT 
WHERE ROLL IN (SELECT ROLL FROM DATABASE WHERE LOCATION='CHAYABITHI') 
 
--UPDATE THE LOCATION = DHAKA OF SECTION B 
 
UPDATE DATABASE 
SET LOCATION ='DHAKA' 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

SELECT * FROM DATABASE 
 
UPDATE DATABASE 
SET PHONE_NUMBER =000 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='C');

SELECT * FROM DATABASE 
 
UPDATE DATABASE 
SET PHONE_NUMBER =000 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='C');

SELECT * FROM DATABASE 
 
---DELETE ALLL INFO FROM DATABASE OF SECTION A 
 
DELETE FROM DATABASE 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='A');

SELECT * FROM DATABASE 
 
---DELETE ALLL INFO FROM DATABASE OF SECTION A 
 
DELETE FROM DATABASE 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='A');

CREATE TABLE DATABASE( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
LOCATION VARCHAR2(20), 
PHONE_NUMBER NUMBER 
);

CREATE TABLE STUDENT( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3) 
);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('TUMI',10,'CHAYABITHI',017);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('HE',9,'CHAYABITHI',016);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('SHE',5,'CHAYABITHI',014);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('US',7,'CHAYABITHI',013);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('WE',4,'CHAYABITHI',018);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('THEY',6,'CHAYABITHI',015);

SELECT * FROM DATABASE;

DROP TABLE DATABASE 
DROP TABLE STUDENT 
 
INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'A')


INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'A');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('WE',4,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('THEY',6,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('THEY',8,'B');

SELECT * FROM STUDENT;

SELECT * FROM DATABASE 
WHERE ROLL>=5 AND ROLL <=10;

SELECT * FROM STUDENT 
WHERE SECTION='B' 
 
--- FIND OUT THE LOCATION , NAME AND PHONE NUMBER OF THE SECTION B STUDENT  
 
 
 
SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (1,5) 
 
--- FIND OUT THE SECTION OF LOCATION CHAYABITHI 
 
SELECT SECTION FROM STUDENT 
WHERE ROLL IN (SELECT ROLL FROM DATABASE WHERE LOCATION='CHAYABITHI') 
 
--UPDATE THE LOCATION = DHAKA OF SECTION B 
 
UPDATE DATABASE 
SET LOCATION ='DHAKA' 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

SELECT * FROM DATABASE 
 
UPDATE DATABASE 
SET PHONE_NUMBER =000 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='C');

SELECT * FROM DATABASE 
 
---DELETE ALLL INFO FROM DATABASE OF SECTION A 
 
DELETE FROM DATABASE 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='A');

CREATE TABLE DATABASE( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
LOCATION VARCHAR2(20), 
PHONE_NUMBER NUMBER 
);

CREATE TABLE STUDENT( 
 
NAME VARCHAR2(30), 
ROLL NUMBER PRIMARY KEY, 
SECTION VARCHAR2(3) 
);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('AMI',1,'CHAYABITHI',019);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('TUMI',10,'CHAYABITHI',017);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('HE',9,'CHAYABITHI',016);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('SHE',5,'CHAYABITHI',014);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('US',7,'CHAYABITHI',013);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('WE',4,'CHAYABITHI',018);

INSERT INTO DATABASE (NAME,ROLL,LOCATION,PHONE_NUMBER) VALUES ('THEY',6,'CHAYABITHI',015);

SELECT * FROM DATABASE;

DROP TABLE DATABASE 
DROP TABLE STUDENT 
 
INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('AMI',1,'A')


INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('TUMI',10,'A');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('HE',9,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('SHE',5,'B');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('US',7,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('WE',4,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('THEY',6,'C');

INSERT INTO STUDENT (NAME,ROLL,SECTION) VALUES ('THEY',8,'B');

SELECT * FROM STUDENT;

SELECT * FROM DATABASE 
WHERE ROLL>=5 AND ROLL <=10;

SELECT * FROM STUDENT 
WHERE SECTION='B' 
 
--- FIND OUT THE LOCATION , NAME AND PHONE NUMBER OF THE SECTION B STUDENT  
 
 
 
SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

SELECT NAME,LOCATION,PHONE_NUMBER FROM DATABASE 
WHERE ROLL IN (1,5) 
 
--- FIND OUT THE SECTION OF LOCATION CHAYABITHI 
 
SELECT SECTION FROM STUDENT 
WHERE ROLL IN (SELECT ROLL FROM DATABASE WHERE LOCATION='CHAYABITHI') 
 
--UPDATE THE LOCATION = DHAKA OF SECTION B 
 
UPDATE DATABASE 
SET LOCATION ='DHAKA' 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='B');

SELECT * FROM DATABASE 
 
UPDATE DATABASE 
SET PHONE_NUMBER =000 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='C');

SELECT * FROM DATABASE 
 
---DELETE ALLL INFO FROM DATABASE OF SECTION A 
 
DELETE FROM DATABASE 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='A');

SELECT * FROM DATABASE;

DELETE FROM DATABASE 
WHERE ROLL IN (SELECT ROLL FROM STUDENT WHERE SECTION='A');

SELECT * FROM DATABASE;

